language: node_js
node_js:
  - "9"
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: 22e34966-3424-4f99-bde2-99822ce8a7c9
  app: game-store-angular